### ISSUE TITLE
shouldComponentUpdate doesn't work properly with config object

### ISSUE THREAD

**Issue by yborunov** [instructure-react/react-tinymce#13]
`shouldComponentUpdate` always returns true for unchanged `config` and `content` props causes component to rerender every time when parent component rerenders. 

`config` object comparison happens against customized version of config object which includes  `selector` and `setup` properties that were added after `_init` method execution.

config prop need to be cloned before adding any extra properties to it for internal needs..

**Comment by mzabriskie** [comment]
Would love to see your PR.

**Comment by yborunov** [comment]
@mzabriskie it's fairly simple
