### ISSUE TITLE
checksum mismatch serverside rendering

### ISSUE THREAD

**Issue by jamesjjk** [instructure-react/react-tinymce#18]
Hey there, the wrapper seems to work well. However for serverside rendering it looks like you are keeping a count:

var count = 0;
module.exports = function uuid() {
  return 'react-tinymce-' + count++;
};

Maybe this can be slightly refactored for those working in an isomorphic setup? The above causes a mismatch for isomorphic apps: figure out why the markup being generated is different on the client or server:
 (client) a id="react-tinymce-0" data-reactid=".12
 (server) a id="react-tinymce-3" data-reactid=".12

**Comment by jamesjjk** [comment]
I found the ID property!!.. Just an FYI I would consider changing line 89 defaultValue={this.props.content} to putting the value in the textArea.. as the attribute defaultValue does not update on an update of the content prop.

**Comment by alex-paterson** [comment]
For anybody else with this issue, manually set an id prop when you render the TinyMCE component.
