### ISSUE TITLE
Inserting links & images unusable inside react-bootstrap Modal component

### ISSUE THREAD

**Issue by sslotsky** [instructure-react/react-tinymce#37]
The editor works fine in other cases, but when rendered inside a react-bootstrap Modal, inserting links and images doesn't work because the inputs can't be focused. Is there a known workaround for this?

![image](https://cloud.githubusercontent.com/assets/374078/17025129/37a7bb0e-4f20-11e6-9fd0-f929a8aba0d2.png)

**Comment by dsbuttery** [comment]
I am also seeing this behavior.   Need a workaround ASAP or will have to abandon TinyMCE for another editor ...

**Comment by sslotsky** [comment]
I found this suggested workaround that has apparently worked for others, but it does not work in my case. Seems quite relevant though.

http://stackoverflow.com/questions/26836103/textbox-not-clickable-in-tinymce-modal-box

**Comment by dsbuttery** [comment]
Thanks.   That doesn't work for me either.   Using React/Redux in our project.

**Comment by sslotsky** [comment]
@dsbuttery I found that bootstrap's `Modal` component has an `enforceFocus` property that you can set to `false` to solve this problem. If it works for you as well I will close this issue.

**Comment by dsbuttery** [comment]
Bingo!   Works like a charm. Thanks!

**Comment by GeorgioWan** [comment]
@sslotsky THANKS for found this solution!!! :joy:
