### ISSUE TITLE
How to configuration lanuage

### ISSUE THREAD

**Issue by yuhaocan** [instructure-react/react-tinymce#67]

**Comment by sushicodeur** [comment]
I came here for what I think is the same problem : how to configure TinyMCE in your own language (fr_FR in my case).

To do so : 

* download your language pack here https://www.tinymce.com/download/language-packages/
* unzip this file and place it on your assets folder so it can be accessed in the browser (in my case, I unziped the `langs` folder right under my root)
* then use TinyMCE component like that :

```
<TinyMCE
    content={post_content}
    config={{
        language: 'fr_FR',
        language_url: '/langs/fr_FR.js',
        ...
    }}
/>
```

Hope this helps
