### ISSUE TITLE
Clear TinyMCE content

### ISSUE THREAD

**Issue by vlysytsia** [instructure-react/react-tinymce#89]
I have TinyMCE component inside my own component 
`<TinyMCE content={this.state.text} config={config} onChange={handleChange} />;`

and update my component state on handleChange function and after submit form clear test value
```
this.setState({
  text: ''
}) 
```

But TinyMCE how previous result. Is it possible clear TinyMCE content?

@brentburg

**Comment by vlysytsia** [comment]
tinymce.activeEditor.setContent(''); clear TinyMCE content. Hope it help somebody)

**Comment by cinder92** [comment]
@volodymyrl  could you explain with code? where did i get tinymce variable?

**Comment by vlysytsia** [comment]
@cinder92  it's global variable - you can get it by `window.tinymce` or `const { tinymce } = window;`
